import { AppDefinition, Contact, DeviceSettings, FileItem, MessageThread, MusicTrack, NoteItem, NotificationItem } from "@/types/android";

export const DEFAULT_SETTINGS: DeviceSettings = {
  darkMode: true,
  themeColor: "#A8C7FA", // Google Pixel Material Blue
  brightness: 90,
  volume: 75,
  wifiEnabled: true,
  bluetoothEnabled: true,
  flashlightEnabled: false,
  dndEnabled: false,
  autoRotate: true,
  airplaneMode: false,
  batterySaver: false,
  screenTimeoutSec: 60,
  navStyle: "gesture",
  wallpaper: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop",
  soundMuted: false,
  phoneSkin: "pixel",
  fontSize: "default",
};

export const WALLPAPERS = [
  {
    id: "abstract-waves",
    name: "Material Wave",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "mountain-dusk",
    name: "Mountain Dusk",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "neon-cyber",
    name: "Neon Glow",
    url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "cosmic-stars",
    name: "Cosmic Space",
    url: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "nature-forest",
    name: "Emerald Forest",
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1000&auto=format&fit=crop",
  },
  {
    id: "dark-minimal",
    name: "Dark Geometry",
    url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop",
  },
];

export const THEME_COLORS = [
  { name: "Pixel Sky", value: "#A8C7FA", darkSurface: "#1F232B", accent: "#7CABF5" },
  { name: "Coral Sunset", value: "#F28B82", darkSurface: "#2C1E20", accent: "#E57373" },
  { name: "Mint Emerald", value: "#81C995", darkSurface: "#1D2821", accent: "#66BB6A" },
  { name: "Material Violet", value: "#D0BCFF", darkSurface: "#272130", accent: "#B388FF" },
  { name: "Sun Amber", value: "#FDD663", darkSurface: "#2B2619", accent: "#FFD54F" },
  { name: "Teal Lagoon", value: "#7BD0C1", darkSurface: "#1B2726", accent: "#4DB6AC" },
];

export const APPS: AppDefinition[] = [
  {
    id: "phone",
    name: "Phone",
    iconName: "Phone",
    bgColor: "bg-emerald-500",
    textColor: "text-white",
    category: "system",
    installed: true,
    dock: true,
  },
  {
    id: "messages",
    name: "Messages",
    iconName: "MessageSquare",
    bgColor: "bg-blue-500",
    textColor: "text-white",
    category: "google",
    installed: true,
    dock: true,
  },
  {
    id: "chrome",
    name: "Chrome",
    iconName: "Compass",
    bgColor: "bg-amber-500",
    textColor: "text-white",
    category: "google",
    installed: true,
    dock: true,
  },
  {
    id: "camera",
    name: "Camera",
    iconName: "Camera",
    bgColor: "bg-slate-700",
    textColor: "text-white",
    category: "system",
    installed: true,
    dock: true,
  },
  {
    id: "playstore",
    name: "Play Store",
    iconName: "ShoppingBag",
    bgColor: "bg-cyan-500",
    textColor: "text-white",
    category: "google",
    installed: true,
    dock: true,
  },
  {
    id: "photos",
    name: "Photos",
    iconName: "Image",
    bgColor: "bg-rose-500",
    textColor: "text-white",
    category: "google",
    installed: true,
    dock: false,
  },
  {
    id: "settings",
    name: "Settings",
    iconName: "Settings",
    bgColor: "bg-zinc-600",
    textColor: "text-white",
    category: "system",
    installed: true,
    dock: false,
  },
  {
    id: "calculator",
    name: "Calculator",
    iconName: "Calculator",
    bgColor: "bg-teal-600",
    textColor: "text-white",
    category: "tools",
    installed: true,
    dock: false,
  },
  {
    id: "clock",
    name: "Clock",
    iconName: "Clock",
    bgColor: "bg-indigo-600",
    textColor: "text-white",
    category: "system",
    installed: true,
    dock: false,
  },
  {
    id: "files",
    name: "Files",
    iconName: "Folder",
    bgColor: "bg-sky-600",
    textColor: "text-white",
    category: "google",
    installed: true,
    dock: false,
  },
  {
    id: "music",
    name: "YT Music",
    iconName: "Music",
    bgColor: "bg-red-600",
    textColor: "text-white",
    category: "media",
    installed: true,
    dock: false,
  },
  {
    id: "games",
    name: "Play Games",
    iconName: "Gamepad2",
    bgColor: "bg-emerald-600",
    textColor: "text-white",
    category: "games",
    installed: true,
    dock: false,
  },
  {
    id: "notes",
    name: "Keep Notes",
    iconName: "StickyNote",
    bgColor: "bg-amber-400",
    textColor: "text-zinc-900",
    category: "google",
    installed: true,
    dock: false,
  },
  {
    id: "recorder",
    name: "Recorder",
    iconName: "Mic",
    bgColor: "bg-red-500",
    textColor: "text-white",
    category: "tools",
    installed: true,
    dock: false,
  },
  {
    id: "youtube",
    name: "YouTube",
    iconName: "Tv",
    bgColor: "bg-red-700",
    textColor: "text-white",
    category: "media",
    installed: true,
    dock: false,
  },
  {
    id: "termux",
    name: "Termux",
    iconName: "Terminal",
    bgColor: "bg-black",
    textColor: "text-emerald-400",
    category: "tools",
    installed: true,
    dock: false,
  },
];

export const INITIAL_CONTACTS: Contact[] = [
  { id: "c1", name: "Gemini AI Assistant", phone: "1-800-GEMINI", avatarColor: "bg-purple-600", favorite: true },
  { id: "c2", name: "Anik (Tusar)", phone: "+880 1712-345678", avatarColor: "bg-blue-600", favorite: true },
  { id: "c3", name: "Google Support", phone: "1-800-555-0199", avatarColor: "bg-emerald-600" },
  { id: "c4", name: "Mom", phone: "+880 1812-987654", avatarColor: "bg-rose-600", favorite: true },
  { id: "c5", name: "Alex (RUET Lab)", phone: "+880 1912-778899", avatarColor: "bg-amber-600" },
  { id: "c6", name: "Dev Team Lead", phone: "+1 415-555-2671", avatarColor: "bg-teal-600" },
];

export const INITIAL_MESSAGES: MessageThread[] = [
  {
    id: "t1",
    contactId: "c1",
    contactName: "Gemini AI Assistant",
    avatarColor: "bg-purple-600",
    unreadCount: 1,
    lastMessageTime: "10:42 AM",
    messages: [
      { id: "m1", sender: "them", text: "Hello Anik! I am your Android AI Assistant. Ask me anything or type a prompt!", time: "10:40 AM" },
      { id: "m2", sender: "me", text: "What's the status of the Android emulator?", time: "10:41 AM" },
      { id: "m3", sender: "them", text: "All 16 Android system applications are loaded and running smoothly on Android 15!", time: "10:42 AM" },
    ],
  },
  {
    id: "t2",
    contactId: "c2",
    contactName: "Anik (Tusar)",
    avatarColor: "bg-blue-600",
    unreadCount: 0,
    lastMessageTime: "Yesterday",
    messages: [
      { id: "m4", sender: "them", text: "Hey! Did you check the new Android Material You UI update?", time: "Yesterday" },
      { id: "m5", sender: "me", text: "Yes, the dynamic themes and smooth gesture navigation are super clean!", time: "Yesterday" },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "n1",
    appId: "messages",
    appName: "Messages",
    title: "Gemini AI Assistant",
    message: "All 16 Android system applications are running smoothly!",
    time: "Just now",
    unread: true,
  },
  {
    id: "n2",
    appId: "playstore",
    appName: "Google Play Store",
    title: "Updates Available",
    message: "4 applications have pending updates available for download.",
    time: "15m ago",
    unread: true,
  },
  {
    id: "n3",
    appId: "photos",
    appName: "Google Photos",
    title: "Memories Ready",
    message: "Rediscover your favorite moments from this week.",
    time: "1h ago",
    unread: false,
  },
];

export const INITIAL_NOTES: NoteItem[] = [
  {
    id: "note-1",
    title: "Android 15 Emulator Roadmap",
    content: "1. Material You dynamic colors\n2. Real camera integration\n3. Full dialer with DTMF tones\n4. Responsive phone frame & full-screen mobile mode\n5. Vercel deployment with zero latency",
    color: "#FEF08A", // yellow
    pinned: true,
    updatedAt: "Today, 11:20 AM",
  },
  {
    id: "note-2",
    title: "RUET Lab Notes",
    content: "Algorithm lab report due next Sunday. Review Numerical Methods interpolation formulas.",
    color: "#BBF7D0", // green
    pinned: false,
    updatedAt: "Yesterday",
  },
];

export const INITIAL_FILES: FileItem[] = [
  { id: "f1", name: "Camera", size: "3 items", type: "folder", date: "Aug 15, 2026" },
  { id: "f2", name: "Downloads", size: "5 items", type: "folder", date: "Aug 15, 2026" },
  { id: "f3", name: "Documents", size: "2 items", type: "folder", date: "Aug 14, 2026" },
  { id: "f4", name: "Music", size: "4 items", type: "folder", date: "Aug 13, 2026" },
  { id: "f5", name: "android_wallpaper_4k.jpg", size: "3.4 MB", type: "image", date: "Today", url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1000&auto=format&fit=crop" },
  { id: "f6", name: "lab_report_final.pdf", size: "1.2 MB", type: "doc", date: "Yesterday" },
  { id: "f7", name: "synthwave_dream.mp3", size: "5.8 MB", type: "audio", date: "Aug 12, 2026" },
];

export const INITIAL_MUSIC: MusicTrack[] = [
  {
    id: "m1",
    title: "Midnight City Lights",
    artist: "Synthwave Odyssey",
    album: "Future Echoes 2026",
    duration: "3:45",
    durationSec: 225,
    coverUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m2",
    title: "Chill Horizon Beats",
    artist: "Lofi Cafe",
    album: "Study & Relax Vol. 4",
    duration: "2:50",
    durationSec: 170,
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=400&auto=format&fit=crop",
  },
  {
    id: "m3",
    title: "Silicon Drive",
    artist: "Cyber Pulse",
    album: "Neon Grid",
    duration: "4:12",
    durationSec: 252,
    coverUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=400&auto=format&fit=crop",
  },
];
